version: '3'
services:
  server:
    build: 
      context: ./server
    restart: unless-stopped     
    environment:
      - NEW_YORK_TIMES_IO_API_KEY=
      - THE_GUARDIAN_IO_API_KEY=
      - NEWSDATA_IO_API_KEY=
      - JWT_SECRET=
  client:
    build: 
      context: ./client
      args:
        - VITE_REST_API=
    restart: unless-stopped     
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - 80:80