version: "3.9"
name: newsfeed
services:
  server:
    container_name: newsfeed_server
    build: 
      context: ./server
    restart: unless-stopped     
    environment:
      - NEW_YORK_TIMES_IO_API_KEY=
      - THE_GUARDIAN_IO_API_KEY=
      - NEWSDATA_IO_API_KEY=
      - JWT_SECRET=
  client:
    container_name: newsfeed_client
    build: 
      context: ./client
      args:
        - VITE_REST_API=http://localhost/api/
    restart: unless-stopped     
  nginx:
    container_name: newsfeed_nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - 80:80